#################################################################
#                                                               #
# Script para levantar plataforma de desarrollo continuo con    #
# los siguientes servicios en contenedores docker:              #
#                                                               #
#    NOMBRE SERVICIO                      PUERTO EN LOCALHOST   #
#  - Nginx                                             80       #
#  - Apache (Aplicaciones PHP)                      48082       #
#  - Tomcat (Aplicaciones JAVA)                     48084       #
#  - Nexus (Repositorio de Componentes)             48081       #
#  - Jenkins (Integraci贸n Continua)                 48080       #
#  - SonarQube (Inspecci贸n de C贸digo)               49000       #
#  - MySQL (Base de Datos de SonarQube)             43306       #
#  - MySQL (Base de Datos de Aplicaciones Web)      43307       #
#                                                               #
#################################################################

version: '2.1'

#################################################################
# Configuracion de Red
#################################################################
networks:
    orovenet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.1.2.0/24
                  gateway: 172.1.2.1


#################################################################
# Configuraci贸n de Servicios
#################################################################
services:

    ########################## NGINX ############################
    nginx:
        image: nginx
        volumes:
            - ${DATA_VOLUMES_PATH}/nginx/html:/usr/share/nginx/html/
            - ${DATA_VOLUMES_PATH}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            orovenet:
                ipv4_address: 172.1.2.10
        extra_hosts:
            - "jenkins:172.1.2.20"
            - "sonarqube:172.1.2.30"
            - "nexus:172.1.2.40"
            - "selenium:172.1.2.50"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"


    ######################## SONARQUBE ##########################
    sonarqube:
        image: sonarqube:6.2
        depends_on:
            - mysql-sonarqube
        depends_on:
            mysql-sonarqube: 
                condition: service_healthy
        links:
            - mysql-sonarqube:mysqlserver
        ports:
            - "49000:9000"
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:mysql://mysqlserver:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
        networks:
            orovenet:
                ipv4_address: 172.1.2.30
        extra_hosts:
            - "nginx:172.1.2.10"
            - "jenkins:172.1.2.20"
            - "nexus:172.1.2.40"
            - "selenium:172.1.2.50"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"
            - "mysqlserver:172.1.2.31"



    ##################### MYSQL-SONARQUBE ########################
    mysql-sonarqube:
        image: mysql:5.7
        ports:
            - "43306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=sonar
            - MYSQL_DATABASE=sonar
            - MYSQL_USER=sonar
            - MYSQL_PASSWORD=sonar
        volumes:
            - ${DATA_VOLUMES_PATH}/mysql-sonarqube/data:/var/lib/mysql
            - ${DATA_VOLUMES_PATH}/mysql-sonarqube/esperar-inicio-servicio-mysql.sh:/bin/esperar-inicio-servicio-mysql.sh
        networks:
            orovenet:
                ipv4_address: 172.1.2.31
        healthcheck:    
            test: "esperar-inicio-servicio-mysql.sh 180" # esperar hasta 3 minutos
        extra_hosts:
            - "nginx:172.1.2.10"
            - "jenkins:172.1.2.20"
            - "nexus:172.1.2.40"
            - "selenium:172.1.2.50"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"

            
    ########################## JENKINS ###########################
    jenkins:
        image: jenkins:2.32.3
        ports:
            - "48080:8080"
        volumes:
            - ${DATA_VOLUMES_PATH}/jenkins:/var/jenkins_home
        networks:
            orovenet:
                ipv4_address: 172.1.2.20
        extra_hosts:
            - "nginx:172.1.2.10"
            - "sonarqube:172.1.2.30"
            - "nexus:172.1.2.40"
            - "selenium:172.1.2.50"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"



    ########################### NEXUS ###########################
    nexus:
        image: clearent/nexus
        ports:
            - "48081:8081"
        volumes:
            - ${DATA_VOLUMES_PATH}/nexus:/nexus-data
        networks:
            orovenet:
                ipv4_address: 172.1.2.40
        extra_hosts:
            - "nginx:172.1.2.10"
            - "jenkins:172.1.2.20"
            - "sonarqube:172.1.2.30"
            - "selenium:172.1.2.50"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"


    ######################## SELENIUM ##########################
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - "44444:4444"
            - "45900:5900"
        networks:
            orovenet:
                ipv4_address: 172.1.2.50
        extra_hosts:
            - "nginx:172.1.2.10"
            - "jenkins:172.1.2.20"
            - "sonarqube:172.1.2.30"
            - "nexus:172.1.2.40"
            - "tomcat:172.1.2.60"
            - "apache:172.1.2.70"



