#################################################################
#                                                               #
# Script para levantar plataforma de desarrollo continuo con    #
# los siguientes servicios en contenedores docker:              #
#                                                               #
#    NOMBRE SERVICIO                      PUERTO EN LOCALHOST   #
#  - Nginx                                             80       #
#  - Apache (Aplicaciones PHP)                      48082       #
#  - Tomcat (Aplicaciones JAVA)                     48084       #
#  - Nexus (Repositorio de Componentes)             48081       #
#  - Jenkins (Integración Continua)                 48080       #
#  - SonarQube (Inspección de Código)               49000       #
#  - MySQL (Base de Datos de SonarQube)             43306       #
#  - MySQL (Base de Datos de Aplicaciones Web)      43307       #
#                                                               #
#################################################################

version: '2.1'
services:


#################################################################
# Contenedor de Nginx
#################################################################
    nginx-webserver:
        image: nginx
        volumes:
            - ./html:/usr/share/nginx/html/
            - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - sonarqube-webapp:sonarqube-server
            - jenkins-webapp:jenkins-server
            - nexus-webapp:nexus-server
        depends_on:
            - sonarqube-webapp
            - jenkins-webapp
            - nexus-webapp


#################################################################
# Contenedor de SonarQube
#################################################################
    sonarqube-webapp:
        image: sonarqube:6.2
        depends_on:
            - sonarqube-database
        depends_on:
            sonarqube-database: 
                condition: service_healthy
        links:
            - sonarqube-database:mysqlserver
        ports:
            - "49000:9000"
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:mysql://mysqlserver:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true


#################################################################
# Contenedor de Base de Datos para SonarQube
#################################################################
    sonarqube-database:
        image: mysql:5.7
        ports:
            - "43306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=sonar
            - MYSQL_DATABASE=sonar
            - MYSQL_USER=sonar
            - MYSQL_PASSWORD=sonar
        volumes:
            - ./scripts:/scripts/
        healthcheck:    
            test: "/scripts/esperar-inicio-servicio-mysql.sh 30"

            
#################################################################
# Contenedor de Jenkins
#################################################################
    jenkins-webapp:
        image: jenkins:2.32.3
        ports:
            - "48080:8080"


#################################################################
# Contenedor de Nexus
#################################################################
    nexus-webapp:
        image: sonatype/nexus3
        ports:
            - "48081:8081"


#################################################################
# Contenedor de Selenium
#################################################################
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
          - "44444:4444"
          - "45900:5900"
        depends_on:
            - nginx-webserver
        links:
            - nginx-webserver